#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH
set -e

build() {
    set -x
    rm -rfv dist
    mkdir dist
    cp -rfv src/float-label.css dist
    # cat tsconfig.json | jq 'del(.include, .compilerOptions.outDir)' >dist/tsconfig.json
    cp -fv README.md package.json dist
    set +x
}

build_docs() {
    set -x
    rm -rfv docs
    vite build --no-minify
    mv -vf dist docs
    sed -i 's|href="/|href="./|g' docs/index.html
    set +x
}

"$@"
