#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH
set -e

build() {
    set -x
    rm -rfv dist
    mkdir dist
    cp -rfv src/float-label.css dist
    # cat tsconfig.json | jq 'del(.include, .compilerOptions.outDir)' >dist/tsconfig.json
    cp -fv README.md package.json dist
    set +x
}

"$@"
