name: 'Test / Build / Release'
on:
  - push
  - pull_request

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Setup node'
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: 'Install depependencies'
        run: npm install --force
      - name: 'Test'
        run: |
          npm run test

  release:
    name: 'Release'
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/next')
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: 'Setup Node'
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: 'Install depependencies'
        run: |
          npm install --force
      - name: 'Build'
        run: |
          npm run build
      - name: 'Release'
        run: |
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: 'Install depependencies'
        run: |
          npm install --force
      - name: 'Build docs'
        run: |
          npm run build_docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
